### ISSUE TITLE
Dex: Internals continued

### ISSUE THREAD

**Issue by bkase** [o1-labs/snarkyjs#402]
Dependencies tracked in other issues
* [x] #136 for reusing a smart contract for two different accounts
* [x] #363 for passing in a verification key to a method; and maybe for passing an account update without introducing another special case for method arguments
* [ ] #431 -- account update structure not working as expected
* [ ] #429 -- return values to transaction block

This issue
* [x] properly prove that we're executing a callback with certain arguments, in the zkApp A (see definitions below). this should be doable by directly using composability for A calling C, getting the party of C and wiring it up to be a child of B. 
```
A - creates callback, passes it to B
B - gets callback, witnesses a superset of parties, does generic check on them
C - is called by the callback
```
